name: car_plaza
description: A Nigerian car buying and selling platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  firebase_storage_web: ^3.6.22
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.2+6
  provider: ^6.0.3
  toastification: ^3.0.2
  cached_network_image: ^3.2.1
  intl: ^0.20.2
  web: ^1.1.1
  js: ^0.6.7
  go_router: ^6.5.7
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  flutter_image_compress: ^2.0.4
  image: ^4.0.17
  firebase_analytics: ^11.4.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/