name: car_plaza
description: A Nigerian car buying and selling platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.1
  firebase_auth: ^4.2.5
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/