name: car_plaza
description: CarPlaz - Buy, Sell, and Discover Cars
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.7.2
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  image_picker: ^1.0.4
  video_player: ^2.7.0
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.2.4
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9
  chewie: ^1.7.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
