name: car_plaza
description: Nigeria's Premier Car Marketplace

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  firebase_core: ^2.18.0
  cloud_firestore: ^4.11.1
  firebase_storage: ^11.6.0
  firebase_auth: ^4.11.1
  firebase_analytics: ^10.4.3
  image_picker: ^0.8.8
  cached_network_image: ^3.3.0
  shimmer: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  url_launcher: ^6.1.11
  share_plus: ^7.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  fluttertoast: ^8.2.1
  uuid: ^3.0.7
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700