name: car_plaza
description: CarPlaz - Buy, Sell, and Discover Cars
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.7.2
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  image_picker: ^1.0.4
  video_player: ^2.7.0
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.8
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.2.4
  file_selector: ^1.0.3
  flutter_svg: ^2.0.9
  chewie: ^1.5.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  mobile_scanner: ^3.0.0
  # flutter_paystack: ^1.0.3
  flutter_local_notifications: ^15.1.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.2.2
  firebase_crashlytics: ^3.5.7
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/google_logo.png
    - assets/onboarding3.png
    - assets/onboarding2.png
    - assets/onboarding1.png
    - assets/placeholder_car.jpg
