name: car_plaza
description: A Nigerian car buying and selling platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.5.0
  firebase_storage_web: ^3.6.22
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.8.0
  image_picker: ^0.8.5+3
  firebase_app_check: ^0.2.2+7
  provider: ^6.0.3
  toastification: ^1.1.0
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  flutter_image_compress: ^2.0.4
  image: ^4.0.17
  google_sign_in: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/