// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfC3g5gIVzSxcUe_BPFiNf61E8EhdimU',
    appId: '1:74696492122:web:de25f54499c71a4ec88463',
    messagingSenderId: '74696492122',
    projectId: 'car-plaza-b9689',
    authDomain: 'car-plaza-b9689.firebaseapp.com',
    storageBucket: 'car-plaza-b9689.firebasestorage.app',
    measurementId: 'G-Q2MKGR6C8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rAyOihJedy5gfOMq5gYUti-ADRUNRFk',
    appId: '1:74696492122:android:1405e6be9692ab40c88463',
    messagingSenderId: '74696492122',
    projectId: 'car-plaza-b9689',
    storageBucket: 'car-plaza-b9689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4g7PgoPnpBu8lHorGLy7IMzsCO3M0Ww',
    appId: '1:74696492122:ios:4e8202a50f28d837c88463',
    messagingSenderId: '74696492122',
    projectId: 'car-plaza-b9689',
    storageBucket: 'car-plaza-b9689.firebasestorage.app',
    iosBundleId: 'com.example.carPlaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4g7PgoPnpBu8lHorGLy7IMzsCO3M0Ww',
    appId: '1:74696492122:ios:4e8202a50f28d837c88463',
    messagingSenderId: '74696492122',
    projectId: 'car-plaza-b9689',
    storageBucket: 'car-plaza-b9689.firebasestorage.app',
    iosBundleId: 'com.example.carPlaza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNfC3g5gIVzSxcUe_BPFiNf61E8EhdimU',
    appId: '1:74696492122:web:341fba7065e8cc89c88463',
    messagingSenderId: '74696492122',
    projectId: 'car-plaza-b9689',
    authDomain: 'car-plaza-b9689.firebaseapp.com',
    storageBucket: 'car-plaza-b9689.firebasestorage.app',
    measurementId: 'G-S66BPPNZQH',
  );
}
